/**
 * A CSS class name or a string containing multiple class names.
 * Typically used to apply styles generated by a styling solution (e.g., CSS Modules, Tailwind, Panda CSS).
 *
 * @example
 * ```ts
 * const baseStyle: RecipeStyle = "btn btn-primary";
 * const variantStyle: RecipeStyle = "bg-blue-500 hover:bg-blue-600";
 * ```
 */
export type RecipeStyle = string;

/**
 * A mapping of variant key to a CSS class string.
 * Each variant option maps to a specific style.
 *
 * @example
 * ```ts
 * const colorVariants: RecipeVariant = {
 *   brand: "bg-brand text-white",
 *   destructive: "bg-red-500 text-white",
 *   outline: "border-2 border-current bg-transparent",
 * };
 * ```
 */
export type RecipeVariant = Record<string, RecipeStyle>;

/**
 * Defines a compound variant: a set of conditions (multiple variant keys)
 * that together produce a specific className.
 *
 * This is useful when you need to apply styles only when two or more
 * variant values are combined (e.g., `variant="solid"` AND `color="brand"`).
 *
 * @property conditions - A record where keys are variant names and values are the variant values.
 * @property className - The style to apply when all conditions match.
 *
 * @example
 * ```ts
 * const compound: RecipeCompoundVariant = {
 *   conditions: { variant: "solid", color: "brand" },
 *   className: "shadow-lg bg-brand-dark",
 * };
 * ```
 */
export interface RecipeCompoundVariant {
  conditions: Record<string, string>;
  className: RecipeStyle;
}

/**
 * Defines the complete styling recipe for a single component.
 *
 * A recipe consists of:
 * - **base**: styles applied to every instance of the component.
 * - **variants**: a set of variant groups (e.g., `size`, `color`, `variant`).
 * - **defaultVariants**: which variant values to use when none are provided.
 * - **compoundVariants**: conditional styles that apply when multiple variant conditions are met.
 *
 * @example
 * ```ts
 * const buttonRecipe: RecipeDefinition = {
 *   base: "inline-flex items-center justify-center rounded font-medium transition-colors",
 *   variants: {
 *     variant: {
 *       solid: "bg-brand text-white hover:bg-brand-dark",
 *       outline: "border-2 border-brand text-brand hover:bg-brand/10",
 *       ghost: "text-brand hover:bg-brand/10",
 *     },
 *     size: {
 *       sm: "px-3 py-1 text-sm",
 *       md: "px-4 py-2 text-base",
 *       lg: "px-6 py-3 text-lg",
 *     },
 *   },
 *   defaultVariants: {
 *     variant: "solid",
 *     size: "md",
 *   },
 *   compoundVariants: [
 *     {
 *       conditions: { variant: "solid", size: "lg" },
 *       className: "shadow-lg",
 *     },
 *   ],
 * };
 * ```
 */
export interface RecipeDefinition {
  /**
   * Base classes applied to every component.
   * These are combined with the variant classes.
   *
   * @example
   * ```ts
   * base: "flex items-center gap-2"
   * ```
   */
  base?: RecipeStyle;

  /**
   * Variant groups.
   * Each key defines a variant prop name (e.g., `size`, `color`).
   * The value is a map of variant option → CSS classes.
   *
   * @example
   * ```ts
   * variants: {
   *   size: {
   *     sm: "text-sm px-3 py-1",
   *     md: "text-base px-4 py-2",
   *   },
   *   color: {
   *     brand: "bg-brand text-white",
   *     destructive: "bg-red-500 text-white",
   *   },
   * }
   * ```
   */
  variants?: Record<string, RecipeVariant>;

  /**
   * Variants used when no explicit prop is provided.
   * Keys must exist in `variants`.
   *
   * @example
   * ```ts
   * defaultVariants: {
   *   size: "md",
   *   color: "brand",
   * }
   * ```
   */
  defaultVariants?: Record<string, string>;

  /**
   * Classes applied when multiple variant conditions match.
   * This is useful for special combinations that require additional styling.
   *
   * @example
   * ```ts
   * compoundVariants: [
   *   {
   *     conditions: { variant: "solid", color: "brand" },
   *     className: "shadow-lg",
   *   },
   *   {
   *     conditions: { size: "lg", color: "destructive" },
   *     className: "uppercase",
   *   },
   * ]
   * ```
   */
  compoundVariants?: RecipeCompoundVariant[];
}

/**
 * A collection of component recipes, keyed by component name.
 * Each component has its own `RecipeDefinition`.
 *
 * @example
 * ```ts
 * const recipes: RecipeCollection = {
 *   Button: buttonRecipe,
 *   Card: cardRecipe,
 *   Input: inputRecipe,
 * };
 * ```
 */
export type RecipeCollection = Record<string, RecipeDefinition>;
